#!/usr/bin/env bash

set -euo pipefail

ANNOTATION_FILE="./annotations/checks.md"

function createAnnotationFile {
  if [[ ! -f ${ANNOTATION_FILE} ]]; then
    local dir
    dir=$(dirname "${ANNOTATION_FILE}")
    mkdir -p "${dir}"
    echo "### Check failures" >> "${ANNOTATION_FILE}"
  fi
}

function logsURL {
  local url
  url="${BUILDKITE_BUILD_URL}#${BUILDKITE_JOB_ID}"
  echo "${url}"
}

function report {
  local pr_num
  pr_num="${BUILDKITE_PULL_REQUEST:-''}"

  createAnnotationFile
  cat << EOF >> ${ANNOTATION_FILE}
* Check \`${BUILDKITE_LABEL}\` failed ❌ - [View logs]($(logsURL))
EOF

  buildkite-agent annotate --style error < ${ANNOTATION_FILE}


  if [[ "${BUILDKITE_PULL_REQUEST_DRAFT:-''}" != "true" &&  ! -z "${pr_num}" ]]; then
    echo "gh pr comment -F \"${ANNOTATION_FILE}\" --edit-last \"${pr_num}\""
  else
    echo "Not creating PR - PR is not DRAFT"
  fi
}

if [[ "${BUILDKITE_COMMAND_EXIT_STATUS:-0}" -ne 0 ]]; then
  set -x
  echo "--- :doctor: writing check failure report"
  report
fi
